const fields = ["endpoint", "model", "apiKey", "target", "resume", "threshold"];
const defaults = { endpoint: "https://api.openai.com/v1", model: "gpt-4o-mini", threshold: 70, pendingJobs: [], configSavedAt: 0, dailySentDate: "", dailySentCount: 0 };
const today = () => new Date().toISOString().slice(0, 10);
function escapeHtml(text) { const div = document.createElement("div"); div.textContent = String(text ?? ""); return div.innerHTML; }
function configState(values) { const missing = [!values.endpoint && "API 地址", !values.model && "模型名称", !values.apiKey && "API Key", !values.resume && "简历"].filter(Boolean); const node = document.getElementById("config-state"); if (missing.length) { node.className = "config-state incomplete"; node.textContent = `本地配置未完成：还需要 ${missing.join("、")}`; } else { node.className = "config-state saved"; node.textContent = `✓ 配置已保存并已回读验证（${values.configSavedAt ? new Date(values.configSavedAt).toLocaleString("zh-CN", { hour12: false }) : "已读取"}） · ${values.model}`; } }
function renderQueue(jobs, values) {
  const queue = document.getElementById("queue"), active = jobs.filter(job => ["pending", "approved", "send-queued", "sending", "send-failed"].includes(job.status));
  const approved = jobs.filter(job => job.status === "approved").length, sent = values.dailySentDate === today() ? values.dailySentCount : 0;
  document.getElementById("queue-summary").textContent = `今日已发送 ${sent}/150 · 已确认 ${approved} 条`;
  document.getElementById("start-send").disabled = !approved || sent >= 150;
  queue.innerHTML = active.length ? active.map(job => { const gaps = (job.skillGaps || []).filter(g => g.gap !== "已具备").slice(0, 2).map(g => escapeHtml(g.skill)).join("、") || "无明显缺口"; const labels = { pending: "待确认", approved: "已确认", "send-queued": "待自动发送", sending: "发送中", "send-failed": "发送失败" }; return `<article class="job-card"><div class="job-top"><b>${escapeHtml(job.title)}</b><span class="score">${job.score}%</span></div><p class="state">${labels[job.status]} · ${escapeHtml(job.verdict)}</p><p class="gaps">技能差距：${gaps}</p><p class="greeting">${escapeHtml(job.greeting)}</p><div class="card-actions"><button data-open="${escapeHtml(job.url)}">打开岗位</button>${job.status === "pending" ? `<button data-approve="${job.id}">确认发送</button>` : ""}<button class="secondary" data-skip="${job.id}">跳过</button></div></article>`; }).join("") : "<p class=\"empty\">暂无待确认岗位。请在 Boss 职位搜索页点击“采集并分析本页”。</p>";
  queue.querySelectorAll("[data-open]").forEach(button => button.onclick = () => chrome.tabs.create({ url: button.dataset.open }));
  queue.querySelectorAll("[data-approve]").forEach(button => button.onclick = () => chrome.runtime.sendMessage({ type: "updateQueueStatus", id: button.dataset.approve, status: "approved" }, load));
  queue.querySelectorAll("[data-skip]").forEach(button => button.onclick = () => chrome.runtime.sendMessage({ type: "updateQueueStatus", id: button.dataset.skip, status: "skipped" }, load));
}
function load() { chrome.storage.local.get(defaults, values => { fields.forEach(id => document.getElementById(id).value = values[id] ?? ""); renderQueue(values.pendingJobs || [], values); configState(values); }); }
function formValues() { return Object.fromEntries(fields.map(id => [id, document.getElementById(id).value.trim()])); }
document.getElementById("save").onclick = () => { const button = document.getElementById("save"), state = document.getElementById("config-state"), values = { ...formValues(), configSavedAt: Date.now() }; button.disabled = true; button.textContent = "正在保存并验证…"; chrome.storage.local.set(values, () => { if (chrome.runtime.lastError) { state.className = "config-state error"; state.textContent = `保存失败：${chrome.runtime.lastError.message}`; button.disabled = false; button.textContent = "保存并验证配置"; return; } chrome.storage.local.get(fields.concat("configSavedAt"), stored => { const valid = fields.every(id => String(stored[id] ?? "") === String(values[id] ?? "")); state.className = valid ? "config-state saved" : "config-state error"; state.textContent = valid ? `✓ 配置已保存并已回读验证（${new Date(stored.configSavedAt).toLocaleString("zh-CN", { hour12: false })}）` : "保存后校验失败，请重新保存。"; button.disabled = false; button.textContent = "保存并验证配置"; }); }); };
document.getElementById("start-send").onclick = () => { if (!confirm("将自动向所有已确认岗位发送招呼语。每条间隔 4–6 秒，且每日最多 150 条。是否开始？")) return; chrome.runtime.sendMessage({ type: "startSending" }, response => { document.getElementById("send-status").textContent = response?.ok ? `已开始自动发送 ${response.count} 条。` : response?.error || "无法启动发送"; load(); }); };
document.getElementById("refresh").onclick = load; chrome.storage.onChanged.addListener(changes => { if (changes.pendingJobs || changes.dailySentCount) load(); }); load();
